export const USER_ROLE = {
  SUPER_ADMIN: "SUPER_ADMIN",
  ADMIN: "ADMIN",
  VENDOR: "VENDOR",
  CUSTOMER: "CUSTOMER",
} as const;

export const USER_STATUS = {
  ACTIVE: "ACTIVE",
  BLOCKED: "BLOCKED",
} as const;

export const ORDER_STATUS = {
  PENDING: "PENDING",
  UNSHIPPED: "UNSHIPPED",
  SHIPPED: "SHIPPED",
  DELIVERED: "DELIVERED",
  CANCELLED: "CANCELLED",
  OUT_OF_DELIVERY: "OUT_OF_DELIVERY",
  REFUNDED: "REFUNDED",
  COMPLETE: "COMPLETE"
} as const;

export const PAYMENT_STATUS = {
  PENDING: "PENDING",
  PAID: "PAID",
  UNPAID: "UNPAID",
  REFUNDED: "REFUNDED",
} as const;

export const VENDOR_HEALTH = {
  HEALTHY: "HEALTHY",
  AT_RISK: "AT_RISK",
  CRITICAL: "CRITICAL",
  SUSPENDED: "SUSPENDED",
} as const;

